ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=SE

# 1. Hemma-WiFi (Högst prioritet)
network={
    ssid="Tele2_5F3556"
    psk="w4hwedx6"
    priority=10
}

# 2. 4G Modem (Lägre prioritet - reserv)
network={
    ssid="4G-UFI-A8DF"
    psk="1234567890"
    priority=5
}
